/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:78e2bc0a-607f-4d6f-8e66-c09ada716759",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_pBiWh2QPZ",
    "aws_user_pools_web_client_id": "3t2d1r5eu99clf0e8rs0nl4jjf",
    "oauth": {
        "domain": "naijagoingabroad-ngaenv.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://naijagoingabroad.com/signin/",
        "redirectSignOut": "https://naijagoingabroad.com/signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "ngabucket194956-ngaenv",
    "aws_user_files_s3_bucket_region": "us-west-2",
    "aws_cloud_logic_custom": [
        {
            "name": "lamdaapi",
            "endpoint": "https://k7zxpvbc63.execute-api.us-west-2.amazonaws.com/ngaenv",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
