/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:e2c541e9-071c-48f0-837d-455e18d8cf2d",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_GvM3Efs1o",
    "aws_user_pools_web_client_id": "1rovp1d2bfeiko344v15j05hlj",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "ngav21e78a8b3cc4f543578f719d56dc031e1c170205-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
